# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: canvascoder
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: automated-serverless
# "service" is the name of this project. This will also be added to your AWS resource names.
service: automated-serverless
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: us-east-2
  environment:
    STAGE: ${env:STAGE, 'prod'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
        - ssm:GetParameterHistory
        - ssm:DescribeParameters
        - ssm:PutParameter
      Resource: arn:aws:ssm:us-east-2:822875511636:parameter//serverless-framework/deployment/database-url


  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - ssm:GetParameter
  #       - ssm:GetParameters
  #       - ssm:GetParametersByPath
  #       - ssm:GetParameterHistory
  #       - ssm:DescribeParameters
  #     Resource: arn:aws:ssm:us-east-2:*:parameter/serverless/framework2/prod/database-url

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - DATABASE_URL
  serverless-offline:
    httpPort: 4000   # Change to any port you want


plugins:
  - serverless-offline
